name: kaiho_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  go_router: ^15.1.2

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2

  # Navigation
  go_router: ^14.6.2

  # Network & Storage
  http: ^1.2.2
  dio: ^5.4.0
  shared_preferences: ^2.3.3
  flutter_dotenv: ^5.1.0

  # Serialization
  json_annotation: ^4.8.1

  # UI
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6

flutter_native_splash:
  image: assets/images/kaiho_verde_full.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/isotipo-kaiho-espiral-blanco.png"
  adaptive_icon_background: "#22412D"
  adaptive_icon_foreground: "assets/images/isotipo-kaiho-espiral-blanco.png"
